import {
  FaGithub,
  FaGitlab,
  FaBitbucket,
  FaStackOverflow,
  FaDev,
  FaMedium,
  FaLinkedin,
  FaXTwitter,
  FaFacebook,
  FaInstagram,
  FaYoutube,
  FaTiktok,
  FaWhatsapp,
  FaTelegram,
  FaDiscord,
  FaSkype,
  FaGlobe,
  FaEnvelope,
  FaPhone,
} from "react-icons/fa6";
import { SiSignal, SiUpwork, SiFiverr, SiFreelancer } from "react-icons/si";

export const SOCIAL_ICON_KEYS = [
  "github",
  "gitlab",
  "bitbucket",
  "stackOverflow",
  "dev",
  "medium",
  "linkedin",
  "x",
  "facebook",
  "instagram",
  "youtube",
  "tiktok",
  "email",
  "phone",
  "whatsApp",
  "telegram",
  "discord",
  "skype",
  "signal",
  "website",
  "upwork",
  "fiverr",
  "freelancer",
] as const;

export type SocialIconKey = (typeof SOCIAL_ICON_KEYS)[number];

export const iconMap: Record<
  string,
  React.ComponentType<{ className?: string; size?: number | string }>
> = {
  github: FaGithub,
  gitlab: FaGitlab,
  bitbucket: FaBitbucket,
  stackoverflow: FaStackOverflow,
  stackOverflow: FaStackOverflow,
  dev: FaDev,
  medium: FaMedium,
  linkedin: FaLinkedin,
  x: FaXTwitter,
  twitter: FaXTwitter,
  facebook: FaFacebook,
  instagram: FaInstagram,
  youtube: FaYoutube,
  tiktok: FaTiktok,
  email: FaEnvelope,
  phone: FaPhone,
  whatsapp: FaWhatsapp,
  whatsApp: FaWhatsapp,
  telegram: FaTelegram,
  discord: FaDiscord,
  skype: FaSkype,
  signal: SiSignal,
  website: FaGlobe,
  upwork: SiUpwork,
  fiverr: SiFiverr,
  freelancer: SiFreelancer,
};
